export const STAFFS_LOADING = "STAFFS_LOADING";
export const STAFFS_FAILED = "STAFFS_FAILED";
export const STAFFS_ADD = "STAFFS_ADD";
export const STAFF_POST = "STAFF_POST";
export const STAFF_PATCH = "STAFF_PATCH";

export const DEPARTMENTS_LOADING = "DEPARTMENTS_LOADING";
export const DEPARTMENTS_FAILED = "DEPARTMENTS_FAILED";
export const DEPARTMENTS_ADD = "DEPARTMENTS_ADD";
